### ISSUE TITLE
Bing.Permissions目前用了一下,发现验证授权那里总过不了。

### ISSUE THREAD

**Issue by qcjxberin** [bing-framework/Bing.NetCore#21]
![image](https://user-images.githubusercontent.com/5792218/67613096-f877a580-f7db-11e9-9221-7e3f4680bf82.png)
Bing.Permissions目前用了一下，但是发觉在下面圈中的地方总是过不了。能否指点下具体的用法。目前就是根据Demo来的，其他都已经实现。

**Comment by qcjxberin** [comment]
已经处理解决了。

**Comment by jianxuanbing** [comment]
> 已经处理解决了。

这个需要设置JWT校验，否则识别不了
![image](https://user-images.githubusercontent.com/7100363/67645867-1f61e300-f966-11e9-902e-fa0ecb5aaa8b.png)

**Comment by qcjxberin** [comment]
现在发现一个问题就是刷新令牌不存在或已过期

**Comment by jianxuanbing** [comment]
> 现在发现一个问题就是刷新令牌不存在或已过期

有没有用缓存呢？因为我是借助了Redis进行存储的

**Comment by qcjxberin** [comment]
有用redis做缓存。关于刷新令牌，你前端有用到定时器吗？

**Comment by jianxuanbing** [comment]
> 有用redis做缓存。关于刷新令牌，你前端有用到定时器吗？

我权限拦截的时候，返回特定的编码。前端做了拦截，如果是超时编码，调用刷新令牌接口

**Comment by qcjxberin** [comment]
特定的编码是指401、402这种吗？

**Comment by jianxuanbing** [comment]
> 特定的编码是指401、402这种吗？

我默认固定了这些编码
![image](https://user-images.githubusercontent.com/7100363/67665199-36bfc100-f9a4-11e9-91dc-55d8de31ce8c.png)

**Comment by qcjxberin** [comment]
那我大概了解了。

**Comment by qcjxberin** [comment]
An item with the same key has already been added. Key: aud  这种错误一般是什么情况下会出现的。

**Comment by jianxuanbing** [comment]
> An item with the same key has already been added. Key: aud 这种错误一般是什么情况下会出现的。

我已经处理重复Key的呢，你看一下你的 缓存 咋处理

**Comment by qcjxberin** [comment]
我的已经解决了。
