### ISSUE TITLE
审计字段能否自定义设置

### ISSUE THREAD

**Issue by fireoao1** [bing-framework/Bing.NetCore#32]
不同项目的数据库字段与实际审计字段不一致。能否在不修改Bing.Core.Domain的前提下修改对应的字段。

**Comment by jianxuanbing** [comment]
可以在 Map 映射当中进行转换处理 将 数据库字段名称 转换为目标 字段。
参考 Id 的设置

**Comment by fireoao1** [comment]
好的 感谢
