### ISSUE TITLE
大佬，常用正则表达式在哪儿。

### ISSUE THREAD

**Issue by newbe36524** [bing-framework/Bing.NetCore#42]
大佬大佬，嘤嘤嘤。
我打算把常用正则表达式集成到我的 Newbe.ObjectVisitor 当中做常用验证进行分发。
内容上我留一个MIT。
求大佬指点。

**Comment by jianxuanbing** [comment]
常用正则地址：[Valid.cs](https://github.com/bing-framework/Bing.Utils/blob/main/src/Bing.Utils/Bing/Helpers/Valid.cs)

**Comment by newbe36524** [comment]
好的大佬，没问题大佬，可以的大佬。等我发布了，我来关这个 issue
