### ISSUE TITLE
-.-

### ISSUE THREAD

**Issue by liangshiw** [bing-framework/Bing.NetCore#6]
大哥不生产代码，，只是代码的搬运工

**Comment by jianxuanbing** [comment]
大部分是Util那边的，不过你这也有一些

**Comment by alexinea** [comment]
前排近距离围观

**Comment by liangshiw** [comment]
嗯，我的项目用的是mit协议。请遵循mit协议内容
https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89
![image](https://user-images.githubusercontent.com/16813853/51104757-f8488380-1821-11e9-9f06-1926a153cceb.png)
或者在readme等介绍中标注来源

**Comment by jianxuanbing** [comment]
会加上的，现在文档都咋更新
