### ISSUE TITLE
单体主站项目Site，引用另个二个独立的类库项目Pms及Pdm时，后注册的，继承AggregateRootMap类没调用到，

### ISSUE THREAD

**Issue by shiqw** [bing-framework/Bing.NetCore#69]
单体主站项目Site，引用另个二个独立的类库项目Pms及Pdm时
在EntityFrameworkCoreModule中，注册

  services.AddPmsDbContext();
  services.AddPdmDbContext();

注册在最前的 AddPmsDbContext的项目，可以正常调用到继承于AggregateRootMap的MapTable的方法
后面注册的，如AddPdmDbContext，就无法正常调用到

请问，这出现的问题在哪里呢？

**Comment by shiqw** [comment]
导致提醒如：Cannot create a DbSet for 'Product' because this type is not included in the model for the context

**Comment by jianxuanbing** [comment]
你是通过`AddxxxxxUnitOfWork`的方式来注册工作单元么？

**Comment by jianxuanbing** [comment]
可以附上片段注册相关的代码？

**Comment by shiqw** [comment]
Tuming.EIS.App 引用了类项目Tuming.PDM.Web和Tuming.PMS.Web


在Tuming.EIS.App项目Startup中注册
&nbsp; &nbsp; &nbsp; services.AddBing()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .AddModule<LogModule&gt;()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .AddModule<MapperModule&gt;()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .AddModule<AppModule&gt;()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .AddModule<AuthenticationModule&gt;()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .AddModule<EntityFrameworkCoreModule&gt;()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .AddModule<CacheModule&gt;();

然后在EntityFrameworkCoreModule类中AddServices顺序注册



&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; services.AddPmsDbContext();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; services.AddPdmDbContext();



AddPmsDbContext方法


&nbsp; &nbsp; &nbsp; &nbsp; public static IServiceCollection AddPmsDbContext(this IServiceCollection services) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; services.AddDbContext<PmsTenantDbContext&gt;();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; services.AddMySqlMultiTenantUnitOfWork<IPmsUnitOfWork, PmsUnitOfWork&gt;(m =&gt; { });
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return services;
&nbsp; &nbsp; &nbsp; &nbsp; }





AddPdmDbContext方法
&nbsp; &nbsp; &nbsp; &nbsp; public static IServiceCollection AddPdmDbContext(this IServiceCollection services)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; services.AddDbContext<PdmTenantDbContext&gt;();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; services.AddMySqlMultiTenantUnitOfWork<IPdmUnitOfWork, PdmUnitOfWork&gt;(m =&gt; { });
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return services;
&nbsp; &nbsp; &nbsp; &nbsp; }



注册在前面的services.AddPmsDbContext();&nbsp;&nbsp;Maps下的DbContext DataSet映射类可以正常使用
而后面注册的AddPdmDbContext，就不能正常使用，比如我调用产品的api时，不会进入ProductMap，导致说DataSet未注册Product






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月12日(星期二) 上午9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bing-framework/Bing.NetCore] 单体主站项目Site，引用另个二个独立的类库项目Pms及Pdm时，后注册的，继承AggregateRootMap类没调用到， (Issue #69)





 
可以附上片段注册相关的代码？
 
&mdash;

**Comment by jianxuanbing** [comment]
你的注册方法应该出错了，因为我是通过泛型注入的`AddDbContext<TService, TImplementation>` 以及`services.TryAddScoped<IUnitOfWork>(t => t.GetService<TImplementation>())`
你的工作单元实现并没有跟`DbContext`没有关联吧?
