### ISSUE TITLE
建议增加appveyor CI并自动发布新版本nuget包

### ISSUE THREAD

**Issue by hanabi1224** [bing-framework/Bing.NetCore#8]

**Comment by hanabi1224** [comment]
https://github.com/bing-framework/Bing.NetCore/pull/9

**Comment by jianxuanbing** [comment]
注册`appveyor`出现了问题，好像现在注册不了了，也没法登录。
![image](https://user-images.githubusercontent.com/7100363/54874508-b5111f00-4e27-11e9-845d-35a439eaba60.png)

**Comment by hanabi1224** [comment]
@jianxuanbing 直接github帐号登录好像不用注册吧

**Comment by jianxuanbing** [comment]
额，我也是用github账号登录。。。但是就是失败了，同上面那个错误提示一样

**Comment by hanabi1224** [comment]
@jianxuanbing  好吧。。没准过两天就好了，另外这个pr里把.csproj写法简化了。。 过两天我又得merge conflict : (

**Comment by hanabi1224** [comment]
@jianxuanbing  travis ci build也没什么问题，还是有几个测试过不了
https://travis-ci.org/hanabi1224/Bing.NetCore/builds/510487939

**Comment by jianxuanbing** [comment]
Travis CI  好像无法识别`\r\n`这样的，单元测试的过程中，基本都是这个报错了
![image](https://user-images.githubusercontent.com/7100363/54880137-a6088c00-4e7c-11e9-8535-f08112d4a950.png)

**Comment by hanabi1224** [comment]
@jianxuanbing  嗯 travis ci是在linux上跑的，可能有些库对linux的兼容有问题吧
